### ISSUE TITLE
Templates - Cannot read property 'match' of undefined 

### ISSUE THREAD

**Issue by Reconix** [Forgeigniter/ForgeIgniter-CI-3.x#21]
/js/templates.js

When trying to edit or add a new template to a module, the selectedModule no longer changes.

Since the update to jQuery 3 this no longer works, but was working previously.

This needs a rewrite anyway but just getting it to function like it did would be a start.

**Comment by HendrikEduard** [comment]
This only affects the Admin area.

**Comment by Reconix** [comment]
True, It affects, 
/admin/pages/add_template/
/admin/pages/edit_template/

Might take a look at this again today, because with this not working you can't even make a basic blog using your own theme.

[Template JS](https://github.com/Forgeigniter/ForgeIgniter-CI-3.x/blob/v2.x/static/js/templates.js)
