### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by axoloth** [Forgeigniter/ForgeIgniter-CI-3.x#22]
Just install the ForgeIgniter-CI-3.x on Windows/Wamp.
After the config screen passed, the database is correctly create, but when i click on "Admin login", i have a 500 error (Internal Server error).

The only thing i have in logs is: 

[Wed Nov 29 23:51:31.414867 2017] [core:error] [pid 5752:tid 828] [client 127.0.0.1:53103] AH00124: Request exceeded the limit of 10 internal redirects due to probable configuration error. Use 'LimitInternalRecursion' to increase the limit if necessary. Use 'LogLevel debug' to get a backtrace.
[Wed Nov 29 23:51:31.414867 2017] [core:debug] [pid 5752:tid 828] core.c(3760): [client 127.0.0.1:53103] AH00121: r->uri = /forge/index.php/forge/index.php/forge/index.php/forge/index.php/forge/index.php/forge/index.php/forge/index.php/forge/index.php/forge/index.php/forge/index.php/admin
[Wed Nov 29 23:51:31.414867 2017] [core:debug] [pid 5752:tid 828] core.c(3766): [client 127.0.0.1:53103] AH00122: redirected from r->uri = /forge/index.php/forge/index.php/forge/index.php/forge/index.php/forge/index.php/forge/index.php/forge/index.php/forge/index.php/forge/index.php/admin
[Wed Nov 29 23:51:31.414867 2017] [core:debug] [pid 5752:tid 828] core.c(3766): [client 127.0.0.1:53103] AH00122: redirected from r->uri = /forge/index.php/forge/index.php/forge/index.php/forge/index.php/forge/index.php/forge/index.php/forge/index.php/forge/index.php/admin
[Wed Nov 29 23:51:31.414867 2017] [core:debug] [pid 5752:tid 828] core.c(3766): [client 127.0.0.1:53103] AH00122: redirected from r->uri = /forge/index.php/forge/index.php/forge/index.php/forge/index.php/forge/index.php/forge/index.php/forge/index.php/admin
[Wed Nov 29 23:51:31.414867 2017] [core:debug] [pid 5752:tid 828] core.c(3766): [client 127.0.0.1:53103] AH00122: redirected from r->uri = /forge/index.php/forge/index.php/forge/index.php/forge/index.php/forge/index.php/forge/index.php/admin
[Wed Nov 29 23:51:31.414867 2017] [core:debug] [pid 5752:tid 828] core.c(3766): [client 127.0.0.1:53103] AH00122: redirected from r->uri = /forge/index.php/forge/index.php/forge/index.php/forge/index.php/forge/index.php/admin
[Wed Nov 29 23:51:31.414867 2017] [core:debug] [pid 5752:tid 828] core.c(3766): [client 127.0.0.1:53103] AH00122: redirected from r->uri = /forge/index.php/forge/index.php/forge/index.php/forge/index.php/admin
[Wed Nov 29 23:51:31.414867 2017] [core:debug] [pid 5752:tid 828] core.c(3766): [client 127.0.0.1:53103] AH00122: redirected from r->uri = /forge/index.php/forge/index.php/forge/index.php/admin
[Wed Nov 29 23:51:31.414867 2017] [core:debug] [pid 5752:tid 828] core.c(3766): [client 127.0.0.1:53103] AH00122: redirected from r->uri = /forge/index.php/forge/index.php/admin
[Wed Nov 29 23:51:31.414867 2017] [core:debug] [pid 5752:tid 828] core.c(3766): [client 127.0.0.1:53103] AH00122: redirected from r->uri = /forge/index.php/admin
[Wed Nov 29 23:51:31.414867 2017] [core:debug] [pid 5752:tid 828] core.c(3766): [client 127.0.0.1:53103] AH00122: redirected from r->uri = /admin

**Comment by Reconix** [comment]
Looks like you'll have to manually setup config, we're still in very early alpha by the way.
"ForgeIgniter/config/config.php"

**Comment by Reconix** [comment]
Let me know how you get on.
