### ISSUE TITLE
Error Number: 1055

### ISSUE THREAD

**Issue by HendrikEduard** [Forgeigniter/ForgeIgniter-CI-3.x#24]
Expression #1 of ORDER BY clause is not in GROUP BY clause and contains nonaggregated column 'newdb.FI_page_blocks.dateCreated' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by

SELECT MAX(blockID) as blockID FROM `FI_page_blocks` WHERE `siteID` = '1' AND `versionID` = '1' GROUP BY `blockRef` ORDER BY `dateCreated` DESC

Filename: libraries/Core.php

Line Number: 239

**Comment by Reconix** [comment]
What version of MySQL are you on ?

Not getting this error on 5.6

Also, you might want to consider: Disabling ONLY_FULL_GROUP_BY

**Comment by HendrikEduard** [comment]
PHP 7.1 and MySQL 5.7.20

I disabled it in phpmyadmin and then on page reload there are a slew of js and 404 errors.

admin:11 GET http://localhost/static/themes/anvil/bower_components/font-awesome/css/font-awesome.min.css net::ERR_ABORTED
admin:13 GET http://localhost/static/themes/anvil/bower_components/Ionicons/css/ionicons.min.css net::ERR_ABORTED
admin:16 GET http://localhost/static/themes/anvil/css/LTE.css net::ERR_ABORTED
admin:26 GET http://localhost/static/themes/anvil/css/skins/skin-anvil-light.css net::ERR_ABORTED
admin:43 GET http://localhost/static/themes/anvil/bower_components/jquery/dist/jquery.min.js net::ERR_ABORTED
admin:59 GET http://localhost/static/themes/anvil/img/logo/fi-logo.jpg 404 (Not Found)
admin:9 GET http://localhost/static/themes/anvil/bower_components/bootstrap/dist/css/bootstrap.min.css net::ERR_ABORTED
admin:316 GET http://localhost/static/themes/anvil/bower_components/Flot/jquery.flot.js net::ERR_ABORTED
admin:318 GET http://localhost/static/themes/anvil/bower_components/Flot/jquery.flot.resize.js net::ERR_ABORTED
admin:320 GET http://localhost/static/themes/anvil/bower_components/Flot/jquery.flot.time.js net::ERR_ABORTED
admin:732 GET http://localhost/static/themes/anvil/plugins/jQueryUI/jquery-ui.min.js net::ERR_ABORTED
admin:734 GET http://localhost/static/themes/anvil/bower_components/bootstrap/dist/js/bootstrap.min.js net::ERR_ABORTED
admin:737 GET http://localhost/static/themes/anvil/js/app.js net::ERR_ABORTED
admin:63 GET http://localhost/static/themes/anvil/img/logo/forgeigniter-logo.jpg 404 (Not Found)
admin:92 GET http://localhost/static/themes/anvil/img/avatar.png 404 (Not Found)
admin:13 GET http://localhost/static/themes/anvil/bower_components/Ionicons/css/ionicons.min.css net::ERR_ABORTED
admin:11 GET http://localhost/static/themes/anvil/bower_components/font-awesome/css/font-awesome.min.css net::ERR_ABORTED
admin:26 GET http://localhost/static/themes/anvil/css/skins/skin-anvil-light.css net::ERR_ABORTED
admin:16 GET http://localhost/static/themes/anvil/css/LTE.css net::ERR_ABORTED
admin:43 GET http://localhost/static/themes/anvil/bower_components/jquery/dist/jquery.min.js net::ERR_ABORTED
jquery-migrate-3.0.0.js:540 Uncaught ReferenceError: jQuery is not defined
    at jquery-migrate-3.0.0.js:540
(anonymous) @ jquery-migrate-3.0.0.js:540
admin:311 GET http://localhost/static/themes/anvil/img/avatar.png 404 (Not Found)
admin:316 GET http://localhost/static/themes/anvil/bower_components/Flot/jquery.flot.js net::ERR_ABORTED
admin:318 GET http://localhost/static/themes/anvil/bower_components/Flot/jquery.flot.resize.js net::ERR_ABORTED
admin:320 GET http://localhost/static/themes/anvil/bower_components/Flot/jquery.flot.time.js net::ERR_ABORTED
jquery.flot.init.js:1 Uncaught ReferenceError: $ is not defined
    at jquery.flot.init.js:1
(anonymous) @ jquery.flot.init.js:1
admin:333 Uncaught ReferenceError: $ is not defined
    at admin:333
(anonymous) @ admin:333
admin:732 GET http://localhost/static/themes/anvil/plugins/jQueryUI/jquery-ui.min.js net::ERR_ABORTED
admin:734 GET http://localhost/static/themes/anvil/bower_components/bootstrap/dist/js/bootstrap.min.js net::ERR_ABORTED
admin:737 GET http://localhost/static/themes/anvil/js/app.js net::ERR_ABORTED
default.js:16 Uncaught ReferenceError: jQuery is not defined
    at default.js:16
(anonymous) @ default.js:16
admin.js:2 Uncaught ReferenceError: $ is not defined
    at admin.js:2
    at admin.js:29
(anonymous) @ admin.js:2
(anonymous) @ admin.js:29
admin:743 
Uncaught ReferenceError: $ is not defined at admin:743

**Comment by Reconix** [comment]
You might get the odd error due to a lot of the JS needing to be updated for jQuery 3 but not 404s or the rest.

Do you mind letting me know what page you were on when getting these?

**Comment by HendrikEduard** [comment]
http://localhost/admin and all links in the admin menu.

Home, Blog, Shop, Wiki, Events & Forums all work.

**Comment by HendrikEduard** [comment]
In Admin/views/header.php in line 471 you have:
 <a href="#"><i class="fa fa-users"></i> <span>Users &amp Groups</span>
it should be:
 <a href="#"><i class="fa fa-users"></i> <span>Users &amp; Groups</span>

I added the ; but nothing changed.

**Comment by Reconix** [comment]
Let me grab a coffee, download a fresh copy from here and test.

**Comment by Reconix** [comment]
I can't reproduce this other than changing file permissions on the folders.

When you go to, for example : 
http://localhost/static/themes/anvil/plugins/jQueryUI/jquery-ui.min.js
You see it's contents ?

Thanks for pointing out the mistake on line 471, that static menu thankfully won't be there much longer.

**Comment by HendrikEduard** [comment]
/*! jQuery UI - v1.11.4 - 2015-03-11
* http://jqueryui.com

This being Localhost all file/folder permissions are 777

**Comment by Reconix** [comment]
Out of curiosity, does the latest commit get rid of some of those errors ?

**Comment by HendrikEduard** [comment]
Failed to load resource: the server responded with a status of 404 (Not Found)
LTE.css Failed to load resource: the server responded with a status of 404 (Not Found)
ionicons.min.css Failed to load resource: the server responded with a status of 404 (Not Found)
skin-anvil-light.css Failed to load resource: the server responded with a status of 404 (Not Found)
jquery.min.js Failed to load resource: the server responded with a status of 404 (Not Found)
bootstrap.min.css Failed to load resource: the server responded with a status of 404 (Not Found)
jquery.flot.js Failed to load resource: the server responded with a status of 404 (Not Found)
jquery.flot.resize.js Failed to load resource: the server responded with a status of 404 (Not Found)
jquery.flot.time.js Failed to load resource: the server responded with a status of 404 (Not Found)
jquery-ui.min.js Failed to load resource: the server responded with a status of 404 (Not Found)
bootstrap.min.js Failed to load resource: the server responded with a status of 404 (Not Found)
app.js Failed to load resource: the server responded with a status of 404 (Not Found)
fi-logo.jpg Failed to load resource: the server responded with a status of 404 (Not Found)
forgeigniter-logo.jpg Failed to load resource: the server responded with a status of 404 (Not Found)
avatar.png Failed to load resource: the server responded with a status of 404 (Not Found)
jquery-migrate-3.0.0.js:540 Uncaught ReferenceError: jQuery is not defined
    at jquery-migrate-3.0.0.js:540
avatar.png Failed to load resource: the server responded with a status of 404 (Not Found)
jquery.flot.js Failed to load resource: the server responded with a status of 404 (Not Found)
jquery.flot.resize.js Failed to load resource: the server responded with a status of 404 (Not Found)
jquery.flot.time.js Failed to load resource: the server responded with a status of 404 (Not Found)
jquery.flot.init.js:1 Uncaught ReferenceError: $ is not defined
    at jquery.flot.init.js:1
(index):333 Uncaught ReferenceError: $ is not defined
    at (index):333
jquery-ui.min.js Failed to load resource: the server responded with a status of 404 (Not Found)
bootstrap.min.js Failed to load resource: the server responded with a status of 404 (Not Found)
app.js Failed to load resource: the server responded with a status of 404 (Not Found)
default.js:16 Uncaught ReferenceError: jQuery is not defined
    at default.js:16
admin.js:2 Uncaught ReferenceError: $ is not defined
    at admin.js:2
    at admin.js:29
(index):723 Uncaught ReferenceError: $ is not defined
    at (index):723
bootstrap.min.css Failed to load resource: the server responded with a status of 404 (Not Found)
font-awesome.min.css Failed to load resource: the server responded with a status of 404 (Not Found)
LTE.css Failed to load resource: the server responded with a status of 404 (Not Found)
ionicons.min.css Failed to load resource: the server responded with a status of 404 (Not Found)
skin-anvil-light.css Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by HendrikEduard** [comment]
And yes http://static/themes/anvil/plugins/jQueryUI/jquery-ui.min.js works.

**Comment by HendrikEduard** [comment]
![screen shot 2018-02-10 at 3 23 38 pm](https://user-images.githubusercontent.com/16320682/36062958-71f42d58-0e76-11e8-9d97-6ef3298414db.png)

**Comment by Reconix** [comment]
If that doesn't fix it then I believe it's a case of playing around with the regex.
